Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box  = "custom-ubuntu"
    config.vm.hostname = "hadoophost"
    config.vm.network :private_network, ip: "192.168.0.10"
    config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 2
    end

    # Copy configuration files
    config.vm.provision "file", source: "/Users/sabyrzhan/projects/HadoopPlayground/output/cars.data", destination: "cars.data"
    config.vm.provision "copy-jar", type: "file", source: "/Users/sabyrzhan/projects/HadoopPlayground/target/HadoopTest-1.0-SNAPSHOT.jar", destination: "HadoopTest-1.0-SNAPSHOT.jar"
    config.vm.provision "file", source: "core-site.xml", destination: "hadoop-3.3.0/etc/hadoop/"
    config.vm.provision "file", source: "hadoop-env.sh", destination: "hadoop-3.3.0/etc/hadoop/"
    config.vm.provision "file", source: "hdfs-site.xml", destination: "hadoop-3.3.0/etc/hadoop/"
    config.vm.provision "file", source: "mapred-site.xml", destination: "hadoop-3.3.0/etc/hadoop/"
    config.vm.provision "file", source: "yarn-site.xml", destination: "hadoop-3.3.0/etc/hadoop/"

    # Configure Hadoop
    $configure_script = <<-SCRIPT
        ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa <<<y 2>&1 >/dev/null && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 0600 ~/.ssh/authorized_keys
        hdfs namenode -format
        start-dfs.sh
        start-yarn.sh
        jps
    SCRIPT
    config.vm.provision "configure-hadoop", type: "shell", inline: $configure_script, privileged: false
end