---
- hosts: all
  become: true
  tasks:
  - name: Install postgres
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - net-tools
      - postgresql
      - postgresql-contrib