host_size=4
Vagrant.configure("2") do |config|
    config.ssh.insert_key = true
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    (1..host_size).each do |i|
        config.vm.define "host#{i}" do |subconfig|
            subconfig.vm.box  = "ubuntu/focal64"
            subconfig.vm.hostname = "postgres#{i}"
            subconfig.vm.network :private_network, ip: "192.168.0.1#{i}"
            subconfig.vm.network "forwarded_port", guest: 5432, host: 5432+i # postgres port
            subconfig.vm.provision "ansible" do |ansible|
                ansible.playbook = "postgres-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.0.1#{i}"
                }
            end
        end
    end
end