Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 1
    end

    config.vm.define "master" do |subconfig|
        subconfig.vm.box  = "ubuntu/focal64"
        subconfig.vm.hostname = "master"
        subconfig.vm.network :private_network, ip: "192.168.0.10"
        subconfig.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
        end
        subconfig.vm.provision "ansible" do |ansible|
            ansible.playbook = "k8s-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.0.10"
            }
        end
    end
    
    (1..3).each do |i|
        config.vm.define "node#{i}" do |subconfig|
            subconfig.vm.box = "ubuntu/focal64"
            subconfig.vm.hostname = "node#{i}"
            subconfig.vm.network :private_network, ip: "192.168.0.#{i + 10}"
            subconfig.vm.provision "ansible" do |ansible|
                ansible.playbook = "k8s-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.0.#{i + 10}"
                }
            end
        end
    end

    # Install avahi on all machines
    config.vm.provision "shell", inline: <<-SHELL
        apt-get install -y avahi-daemon libnss-mdns
    SHELL
end