node_size = 1

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
  end

  config.vm.define "master" do |subconfig|
      subconfig.vm.box  = "ubuntu/focal64"
      subconfig.vm.hostname = "master"
      subconfig.vm.network :private_network, ip: "192.168.0.10"
      subconfig.vm.provision "ansible" do |ansible|
        ansible.playbook = "docker-playbook.yml"
      end
      subconfig.vm.provision "ansible" do |ansible|
        ansible.playbook = "kube-common.yml"
        ansible.extra_vars = {
            node_ip: "192.168.0.10"
        }
      end
      subconfig.vm.provision "ansible" do |ansible|
          ansible.playbook = "master-playbook.yml"
          ansible.extra_vars = {
              node_ip: "192.168.0.10"
          }
      end
      subconfig.vm.provision "ansible" do |ansible|
        ansible.playbook = "metallb-playbook.yml"
    end
  end

  # (1..node_size).each do |i|
  #     config.vm.define "node#{i}" do |subconfig|
  #         subconfig.vm.box = "ubuntu/focal64"
  #         subconfig.vm.hostname = "node#{i}"
  #         subconfig.vm.network :private_network, ip: "192.168.0.#{i + 10}"
  #         subconfig.vm.provision "ansible" do |ansible|
  #           ansible.playbook = "docker-playbook.yml"
  #         end
  #         subconfig.vm.provision "ansible" do |ansible|
  #           ansible.playbook = "kube-common.yml"
  #           ansible.extra_vars = {
  #               node_ip: "192.168.0.#{i + 10}"
  #           }
  #         end
  #         subconfig.vm.provision "ansible" do |ansible|
  #             ansible.playbook = "node-playbook.yml"
  #             ansible.extra_vars = {
  #                 node_ip: "192.168.0.#{i + 10}"
  #             }
  #         end
  #     end
  # end
end